apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore
  labels:
    app: petstore
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1717566974395
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstore
  template:
    metadata:
      labels:
        app: petstore
    spec:
      containers:
        - name: petstore
          image: petstoredemo.azurecr.io/image-workflow-1717566974395:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
